# Use postgres/example user/password credentials
version: '3.1'

services:

  postgresdb:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef